name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - uses: gradle/actions/setup-gradle@v5

      - name: Build
        run: |
          ./gradlew :app:jar
          mv app/build/libs/app.jar calc.jar

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: calc.jar
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
